app:
  current-weather-service:
    api-token: cc7c19a929d8471dbc5124457230610
    base-url: https://api.weatherapi.com/v1
  admin-password: cucumber

spring:
  liquibase:
    change-log: classpath:changelog/changelog-root.xml
  datasource:
    url: jdbc:h2:mem:maindb
    username: server
    password: password
    driver-class-name: org.h2.Driver
    hikari:
      connection-timeout: 3000
      maxLifetime: 600000
  h2:
    console:
      enabled: true

resilience4j.ratelimiter:
  instances:
    current-weather:
      limitForPeriod: 5
      limitRefreshPeriod: 5s
      timeoutDuration: 100ms
      registerHealthIndicator: true
      eventConsumerBufferSize: 100
