app:
  current-weather-service:
    api-token:
    base-url: https://api.weatherapi.com/v1
  cache:
    course:
      size: 2
  moving-average:
    cities:
      - Moscow
      - Saint-Petersburg
      - Samara
      - Yekaterinburg
      - Omsk
    cron-password: cucumber

spring:
  liquibase:
    change-log: classpath:changelog/changelog-root.xml
  datasource:
    url: jdbc:h2:mem:maindb
    username: server
    password: password
    driver-class-name: org.h2.Driver
    hikari:
      connection-timeout: 3000
      maxLifetime: 600000
  h2:
    console:
      enabled: true
  kafka:
    consumer:
      auto-offset-reset: earliest
      bootstrap-servers: localhost:29092
      group-id: 1
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: pan.artem.tinkoff.service.movingaverage.event
    producer:
      acks: -1
      bootstrap-servers: localhost:29092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

resilience4j.ratelimiter:
  instances:
    current-weather:
      limitForPeriod: 5
      limitRefreshPeriod: 5s
      timeoutDuration: 100ms
      registerHealthIndicator: true
      eventConsumerBufferSize: 100
